/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_coffee_engine_CoffeeEngine */

#ifndef _Included_io_coffee_engine_CoffeeEngine
#define _Included_io_coffee_engine_CoffeeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_coffee_engine_CoffeeEngine
 * Method:    Test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_coffee_1engine_CoffeeEngine_Test
  (JNIEnv *, jclass);

/*
 * Class:     io_coffee_engine_CoffeeEngine
 * Method:    TestVulkan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_coffee_1engine_CoffeeEngine_TestVulkan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
