/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_coffee_engine_test_TestUtil */

#ifndef _Included_io_coffee_engine_test_TestUtil
#define _Included_io_coffee_engine_test_TestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_coffee_engine_test_TestUtil
 * Method:    TestOpenGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_coffee_1engine_test_TestUtil_TestOpenGL
  (JNIEnv *, jclass);

/*
 * Class:     io_coffee_engine_test_TestUtil
 * Method:    TestVulkan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_coffee_1engine_test_TestUtil_TestVulkan
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
