/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_coffee_engine_Window */

#ifndef _Included_io_coffee_engine_Window
#define _Included_io_coffee_engine_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_coffee_engine_Window
 * Method:    nCreateWindow
 * Signature: ()Lio/coffee_engine/Window;
 */
JNIEXPORT jobject JNICALL Java_io_coffee_1engine_Window_nCreateWindow
  (JNIEnv *, jclass);

/*
 * Class:     io_coffee_engine_Window
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_coffee_1engine_Window_run
  (JNIEnv *, jobject);

/*
 * Class:     io_coffee_engine_Window
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_coffee_1engine_Window_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
